#!/bin/sh

DISTRO=$(awk '{print $1}' /etc/issue | tr -d "\n")
if [ "$DISTRO" == "Arch" ]; then
  sudo pacman -S helix --noconfirm
  exit 0
fi

[[ -d $INSTALL_PATH ]] || mkdir -p $INSTALL_PATH
# Fetch the latest release information from the Helix GitHub repository
latest_release=$(curl -s https://api.github.com/repos/helix-editor/helix/releases/latest)

# Extract the URL for the desired asset (e.g., Linux binary)
asset_url=$(echo "$latest_release" | grep -Eo 'https://[^"]+helix-[^"]+-x86_64.linux.tar.xz')

# Alternatively, for tar.gz (adjust the pattern according to the naming convention)
# asset_url=$(echo "$latest_release" | grep -Eo 'https://[^"]+helix-[^"]+-x86_64-linux.tar.xz')

echo $asset_url

(curl -L -o /tmp/helix.tar.xz "$asset_url" || wget -O /tmp/helix.tar.xz "$asset_url") && \

# Extract the tarball to /tmp and capture the output
extracted_paths=$(tar xvf /tmp/helix.tar.xz -C /tmp)

# Get the first extracted item
first_extracted_item=$(echo "$extracted_paths" | head -n 1)

# Construct the full path
extracted_path="/tmp/$first_extracted_item"

# Output the path
echo "The first extracted path is: $extracted_path"

sudo cp $extracted_path/hx /usr/bin/helix || cp $extracted_path/hx .local/bin/hx
[[ -d "/usr/lib/share/helix" ]] || mkdir -p "/usr/lib/share/helix" 
[[ -d "/usr/share/bash-completion/completions" ]] || mkdir -p "/usr/share/bash-completion/completions" 

sudo cp -r $extracted_path/runtime /usr/lib/share/helix
sudo cp  $extracted_path/contrib/completion/hx.bash /usr/share/bash-completion/completions/helix
