#!/bin/bash
install() {
  echo debug $@
  cd $1
  UNPACK=$(unpack $2)
  echo $UNPACK
  echo sudo cp $UNPACK/numbat /usr/bin/numbat
  [[ -d /usr/share/numbat/modules ]] || sudo mkdir -p /usr/share/numbat/modules
  echo sudo cp -r $UNPACK/modules/* /usr/share/numbat/modules/
}

uninstall(){
  sudo rm -rf /usr/bin/numbat
  sudo rm -rf /usr/share/numbat
}

$@
