#!/bin/bash
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Set variable for bash config dir (Imma lazy)
_B_CONF=$HOME/.config/bash

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# Enable fuzzy history search
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Disable case sensitive completion
bind 'set completion-ignore-case on'

# Display a list of the matching files
bind 'set show-all-if-ambiguous on'

# If there are multiple matches for completion, Tab should cycle through them
bind '"\C-f": menu-complete'

# Perform partial (common) completion on the first Tab press, only start
# cycling full results on the second Tab press (from bash version 5)
# bind "set menu-complete-display-prefix on"

# Load colors for ls
source ~/.config/bash/.dir_colors

# Get Distro name
___DISTRO=$(awk '{print $1}' /etc/issue | tr -d "\n")

# Load Prompt stuff
source $_B_CONF/scripts/git-prompt.sh
source ~/.config/bash/prompt

# Load aliases
if [ -d "$HOME/.config/bash/aliases/" ]; then
    for file in "$HOME/.config/bash/aliases/"*; do
        [ -f "$file" ] && source "$file"
    done
fi


# The most important thing
fastfetch 2> /dev/null || (
    echo -ne "Nya $HOSTNAME\n\n\nUwU\n\n"

echo " ((      /|_/|"
echo " \\\\.._.'  , ,\\"
echo "  /\\ | '.__ v /"
echo " (_ .   /   \"   "     
echo "  ) _)._  _ /"
echo " '.\\ \\|( / ( mrf" 
echo "   '' ''\\\\ \\\\"
echo -ne "\n\n"    
)
