#!/bin/bash
#
# ~/.bashrc
#

SOURCE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Set variable for bash config dir (Imma lazy)
_B_CONF="$SOURCE/.config/bash"

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# Enable fuzzy history search
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Disable case sensitive completion
bind 'set completion-ignore-case on'

# Display a list of the matching files
bind 'set show-all-if-ambiguous on'

# If there are multiple matches for completion, Tab should cycle through them
bind '"\C-f": menu-complete'

# Perform partial (common) completion on the first Tab press, only start
# cycling full results on the second Tab press (from bash version 5)
# bind "set menu-complete-display-prefix on"

# Load colors for ls
source $_B_CONF/dir_colors

# Get Distro name
___DISTRO=$(awk '{print $1}' /etc/issue | tr -d "\n")

# Load Prompt stuff
source $_B_CONF/scripts/git-prompt.sh
source $_B_CONF/prompt

# Load aliases
if [ -d "$_B_CONF/aliases/" ]; then
    for file in "$_B_CONF/aliases/"*; do
        [ -f "$file" ] && source "$file"
    done
fi

# import paths
export PATH=$PATH:$(whoami)/.local/bin
if [[ "$(whoami)" == "root" ]]; then
    ADDPATHS="$SOURCE/.local/bin"
    export PATH=$PATH:$ADDPATHS
fi

unset SOURCE

# The most important thing
if [[ "$(whoami)" != "root" ]]; then
    (fastfetch 2> /dev/null || (
    echo -ne "Nya $HOSTNAME\n\n\nUwU\n\n"

echo " ((      /|_/|"
echo " \\\\.._.'  , ,\\"
echo "  /\\ | '.__ v /"
echo " (_ .   /   \"   "
echo "  ) _)._  _ /"
echo " '.\\ \\|( / ( mrf"
echo "   '' ''\\\\ \\\\"
echo -ne "\n\n"
)); fi
