#!/bin/bash
source $_B_CONF/colors
source $_B_CONF/scripts/git-prompt.sh

if [ "$USER" == "root" ]; then
  USERCOLOR="${MAGENTA}"
  PROMPT_BG="\033[48;5;232m"
else
  USERCOLOR="${YELLOW}"
  PROMPT_BG=""
fi

if [[ -f "$_B_CONF/.hostcolor" ]]; then
  HOSTCOLOR=$(hex_to_rgb `cat $_B_CONF/.hostcolor`)
fi

case $___DISTRO in
    "arch"      )       BRACKET_COLOR=$(hex_to_rgb 1793d1)
                        PWD_COLOR=$(hex_to_rgb 1793d1)           ;;
    "alpine"    )       BRACKET_COLOR=$(hex_to_rgb 005880)
                        PWD_COLOR=$(hex_to_rgb 005880)           ;;
    "debian"    )       BRACKET_COLOR=$(hex_to_rgb ce0056)
                        PWD_COLOR=$(hex_to_rgb ce0056)           ;;
    "fedora"    )       BRACKET_COLOR=$(hex_to_rgb 3c6eb4)
                        PWD_COLOR=$(hex_to_rgb 3c6eb4)           ;;
    "gentoo"    )       BRACKET_COLOR=$(hex_to_rgb 54487a)
                        PWD_COLOR=$(hex_to_rgb 54487a)           ;;
    "linuxmint" )       BRACKET_COLOR=$(hex_to_rgb 86be43)
                        PWD_COLOR=$(hex_to_rgb 86be43)           ;;
    "nixos"     )       BRACKET_COLOR=$(hex_to_rgb 5277c3)
                        PWD_COLOR=$(hex_to_rgb 5277c3)           ;;
    "popos"     )       BRACKET_COLOR=$(hex_to_rgb 48b9c7)
                        PWD_COLOR=$(hex_to_rgb 48b9c7)           ;;
    "ubuntu"    )       BRACKET_COLOR=$(hex_to_rgb e95420)
                        PWD_COLOR=$(hex_to_rgb e95420)           ;;
    "debian"    )       BRACKET_COLOR=$(hex_to_rgb ce0056)
                        PWD_COLOR=$(hex_to_rgb ce0056)           ;;
               *)       BRACKET_COLOR=$WHITE  ; PWD_COLOR=$WHITE ;;
esac

case $___DISTRO in
    "arch"      )       DISTRO_LOGO=" " ;;
    "alpine"    )       DISTRO_LOGO=" " ;;
    "debian"    )       DISTRO_LOGO=" " ;;
    "centos"    )       DISTRO_LOGO=" " ;;
    "fedora"    )       DISTRO_LOGO=" " ;;
    "gentoo"    )       DISTRO_LOGO=" " ;;
    "linuxmint" )       DISTRO_LOGO="󰣭 " ;;
    "opensuse"  )       DISTRO_LOGO=" " ;;
    "nixos"     )       DISTRO_LOGO=" " ;;
    "ubuntu"    )       DISTRO_LOGO=" " ;;
    "freebsd"   )       DISTRO_LOGO=" " ;;
               *)       DISTRO_LOGO=" " ;;
esac

__IS_TMUX() {
  if [[ -n $TMUX ]] then
    echo "${BRACKET_COLOR} "
  else
    echo "$BRACKET_COLOR$DISTRO_LOGO"
  fi
}


incognito() {
  if [[ "$1" == "check" ]]; then
    if [[ "$HISTFILE" == "/dev/null" ]]; then
      echo "👻"
    fi
  else
    if [[ "$HISTFILE" == "/dev/null" ]]; then
      HISTFILE="$HOME/.bash_history"
      set -o history
    else
      HISTFILE="/dev/null"
      set +o history     
    fi
  fi
}

__move_cursor_to_end() {
  echo -ne "\n"
  tput cup $(($(tput lines) -2 )) 0
}


___HOSTICON() {
  if [[ -f $_B_CONF/.hosticon ]]; then
    cat $_B_CONF/.hosticon
  fi
}


___SUDO_ACTIVE() {
  if [ "$USER" == root ]; then
    echo "🌱"
  else
    sudo -n true 2>/dev/null && echo -ne "$BRIGHT_RED🍄"
  fi
}

export PS1="\$(__move_cursor_to_end)$(__IS_TMUX)${PROMPT_BG}${BRACKET_COLOR}[\$(___SUDO_ACTIVE)\$(incognito check)${USERCOLOR}\u${BRACKET_COLOR}]${RESET}${BRACKET_COLOR}${PROMPT_BG}[${USERCOLOR}${HOSTCOLOR}$(___HOSTICON)\h${BRACKET_COLOR}]${YELLOW}[${PWD_COLOR}\w${YELLOW}]${RESET}\$(__git_ps1)\\n└─▪ "
unset HOSTCOLOR
unset -f ___HOSTICON





