#!/bin/bash
source $_B_CONF/colors
source $_B_CONF/scripts/git-prompt.sh

if [ "$USER" == "root" ]; then
  USERCOLOR="${MAGENTA}"
  PROMPT_BG="\033[48;5;232m"
else
  USERCOLOR="${YELLOW}"
  PROMPT_BG=""
fi

if [[ -f "$_B_CONF/.hostcolor" ]]; then
  HOSTCOLOR=$(hex_to_rgb `cat $_B_CONF/.hostcolor`)
fi

case $___DISTRO in
    "arch"  )       BRACKET_COLOR=$BLUE ; PWD_COLOR=$BLUE    ;;
    "debian")       BRACKET_COLOR=$RED  ; PWD_COLOR=$RED     ;;
           *)       BRACKET_COLOR=$RED  ; PWD_COLOR=$RED     ;;
esac

__IS_TMUX() {
  [[ -n $TMUX ]] && echo "${CYAN} "
}


incognito() {
  if [[ "$1" == "check" ]]; then
    if [[ "$HISTFILE" == "/dev/null" ]]; then
      echo "👻"
    fi
  else
    if [[ "$HISTFILE" == "/dev/null" ]]; then
      HISTFILE="$HOME/.bash_history"
      set -o history
    else
      HISTFILE="/dev/null"
      set +o history     
    fi
  fi
}

__move_cursor_to_end() {
  echo -ne "\n"
  tput cup $(($(tput lines) -2 )) 0
}


___HOSTICON() {
  if [[ -f $_B_CONF/.hosticon ]]; then
    cat $_B_CONF/.hosticon
  fi
}


___SUDO_ACTIVE() {
  if [ "$USER" == root ]; then
    echo "🌱"
  else
    sudo -n true 2>/dev/null && echo -ne "$BRIGHT_RED🍄"
  fi
}

export PS1="\$(__move_cursor_to_end)$(__IS_TMUX)${PROMPT_BG}${BRACKET_COLOR}[\$(___SUDO_ACTIVE)\$(incognito check)${USERCOLOR}\u${BRACKET_COLOR}]${RESET}${BRACKET_COLOR}${PROMPT_BG}[${USERCOLOR}${HOSTCOLOR}$(___HOSTICON)\h${BRACKET_COLOR}]${YELLOW}[${PWD_COLOR}\w${YELLOW}]${RESET}\$(__git_ps1)\\n└─▪ "
unset HOSTCOLOR
unset -f ___HOSTICON





