#!/bin/bash
ls() {
	clear
	echo
	_ARGS=""
	_DIRS=()
	_SEARCH=($@)
	for i in "${_SEARCH[@]}"; do
		if [[ "$i" == -* ]]; then
	  	_ARGS="$ARGS $i"
	  else
	  	_DIRS+=($i)
	  fi
	done


	[[ ${#_DIRS[@]} -eq 0 ]] && _DIRS=("$PWD")
	WIDTH="$(tput cols)"
	for x in ${_DIRS[@]}; do
			echo -e "${GREEN}  $x${RESET}"
			printf "${GREEN}▔%.0s" $(seq 1 "$WIDTH")
			echo -en "${RESET}"
			lsd --group-dirs=first $_ARGS "$x" || \
			/usr/bin/ls --colors="auto" $_ARGS "$x"
			printf "${BLUE}═%.0s" $(seq 1 "$WIDTH")
			echo -e "${RESET}\n"
	done
	tput cup $(($(tput lines) -2 )) 0
}
