#!/bin/bash
#
# Replaces [sudo su] so I get my toys for those rare occasions i have
# to run as root
# 

SUDOPATH="$(command -v sudo)"

sudo() {
        if [ "$1" == "su" ] && [ -z $2 ]; then
          sudo -E bash
        else
          $SUDOPATH $@
        fi
}
